{{- if .Values.clusterCredentialRotator.enabled }}
{{- $serviceAccountName := .Values.clusterCredentialRotator.serviceAccount.name | default "cluster-credential-rotator" }}
{{- $configMapName := printf "%s-script" $serviceAccountName }}
---
{{- if .Values.clusterCredentialRotator.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $serviceAccountName }}
  namespace: {{ .Release.Namespace }}
---
{{- end }}

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $serviceAccountName }}
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs:
      - get
      - list
      - patch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $serviceAccountName }}
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ $serviceAccountName }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ $serviceAccountName }}
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $configMapName }}
  namespace: {{ .Release.Namespace }}
data:
  cluster-credential-rotator.sh: |-
    {{- tpl ($.Files.Get "script/cluster-credential-rotator.tmpl") . | nindent 4 }}

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ $serviceAccountName }}
  namespace: {{ .Release.Namespace }}
spec:
  schedule: {{ .Values.clusterCredentialRotator.schedule | quote }}
  concurrencyPolicy: {{ .Values.clusterCredentialRotator.concurrencyPolicy }}
  suspend: {{ .Values.clusterCredentialRotator.suspend | default false }}

  failedJobsHistoryLimit: {{ .Values.clusterCredentialRotator.failedJobsHistoryLimit }}
  successfulJobsHistoryLimit: {{ .Values.clusterCredentialRotator.successfulJobsHistoryLimit }}

  {{- with .Values.clusterCredentialRotator.startingDeadlineSeconds }}
  startingDeadlineSeconds: {{ . }}
  {{- end }}

  jobTemplate:
    spec:
      backoffLimit: {{ .Values.clusterCredentialRotator.backoffLimit | default 1 }}

      {{- with .Values.clusterCredentialRotator.activeDeadlineSeconds }}
      activeDeadlineSeconds: {{ . }}
      {{- end }}

      template:
        spec:
          restartPolicy: Never
          serviceAccountName: {{ $serviceAccountName }}

          containers:
            - name: cluster-credential-rotator
              image: "{{ .Values.clusterCredentialRotator.image.repository }}:{{ .Values.clusterCredentialRotator.image.tag }}"
              imagePullPolicy: {{ .Values.clusterCredentialRotator.image.pullPolicy }}

              command:
                - sh
                - /script/cluster-credential-rotator.sh

              volumeMounts:
                - name: script
                  mountPath: /script
                  readOnly: true

              {{- with .Values.clusterCredentialRotator.resources }}
              resources:
                {{- toYaml . | nindent 16 }}
              {{- end }}

          volumes:
            - name: script
              configMap:
                name: {{ $configMapName }}
                defaultMode: 0555
{{- end }}
