---
apiVersion: v2
name: observability-poc-alloy
description: Alloy collector for the centralized observability PoC
type: application
version: 0.1.0

dependencies:
  - name: alloy
    alias: collector
    repository: https://grafana.github.io/helm-charts
    version: 1.12.1
