---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability-poc-hub-pki
  namespace: argocd
spec:
  project: observability-poc
  source:
    repoURL: https://github.com/Rana-Ashar/kubara-local-testing.git
    targetRevision: main
    path: observability-poc/hub/pki
  destination:
    name: hub-cluster
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
