---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability-poc-spoke-1-alloy
  namespace: argocd
spec:
  project: hub-cluster-local

  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: alloy
      targetRevision: 1.12.1
      helm:
        releaseName: spoke-1-alloy
        valueFiles:
          - $values/observability-poc/spoke/alloy/values.yaml

    - repoURL: https://github.com/Rana-Ashar/kubara-local-testing.git
      targetRevision: main
      ref: values

  destination:
    name: spoke-1
    namespace: observability

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
